[project]
name = "atlas-linux-tips"
version = "1.0.0"
description = "ATLAS Linux Tips Fortune File"
channels = ["conda-forge"]
platforms = ["osx-64", "osx-arm64", "linux-64"]

[dependencies]
python = ">=3.14.0,<3.15"

[tasks]
build = "strfile atlas-tips atlas-tips.dat"
test = { cmd = "fortune ./atlas-tips", depends-on = ["build"] }
clean = "rm -f atlas-tips.dat"

[pypi-dependencies]
pnu-strfile = ">=1.0.3, <2"
fortune = ">=1.1.1, <2"
