on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Install fortune (and strfile)
        run: |
          sudo apt-get update
          sudo apt-get install -y fortune-mod

      - name: Build .dat file
        run: |
          strfile ./atlas-tips ./atlas-tips.dat
          ls -lh ./atlas-tips.dat

      - name: Test
        run: fortune $PWD/atlas-tips

      - name: Test random tips uniqueness
        run: |
          TOTAL_TIPS=$(grep '^%$' atlas-tips | wc -l)        # total tips in the file
          SAMPLE_SIZE=50        # number of random tips to sample
          MAX_REPEAT=2          # tolerate <= 2 repeats

          echo "Sampling $SAMPLE_SIZE random tips from $TOTAL_TIPS available tips..."
          tips=$(for i in $(seq 1 $SAMPLE_SIZE); do
            fortune $PWD/atlas-tips | head -n 1
          done)

          echo "$tips" | sort | uniq -c | sort -nr

          repeats=$(echo "$tips" | sort | uniq -c | awk -v max=$MAX_REPEAT '$1>max {sum+=$1} END {print sum+0}')
          if [ "$repeats" -gt 0 ]; then
            echo "❌ Found $repeats tip(s) repeated more than $MAX_REPEAT times in $SAMPLE_SIZE samples"
            exit 1
          else
            echo "✅ Randomness test passed (no tip repeated more than $MAX_REPEAT times)"
          fi

      - name: Commit and push
        run: |
          git add -f atlas-tips.dat
          if ! git diff-index --quiet HEAD; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "regenerate atlas-tips.dat"
            git push
          else
            echo "✅ atlas-tips.dat is up to date!"
          fi

